In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import holidays
import matplotlib.pyplot as plt
import re
engine = create_engine("postgresql+psycopg2://intern_new:internpass_new@localhost:5434/intern_db_new")

# Metrica #1. Promedio Diario de Conversaciones

In [3]:
sentencia = "SELECT * FROM conversations WHERE created_at >= '2025-11-01'"

year_rp = 2026
month_rp = 1

co_holidays = holidays.Colombia(years=year_rp)
co_holidays_dt = pd.to_datetime(list(co_holidays))

df = pd.read_sql(sentencia, engine)
df['created_at'] = pd.to_datetime(df['created_at'])

df = df[(df['created_at'].dt.year == year_rp) & (df['created_at'].dt.month == month_rp)]
df = df.sort_values(['id', 'created_at'])

df['holiday'] = df['created_at'].dt.normalize().isin(co_holidays_dt)


contactos = pd.read_sql("SELECT * FROM contacts WHERE name ~ '[A-Za-z]'", engine)
ids_ignorar_contactos = contactos['id'].unique()
ids_ignorar_contactos = ids_ignorar_contactos.tolist()

#total cantidad datos sin filtrar
cantidad_datos_sin_filtrar = len(df)

ids_conversaciones_ignorar = df.loc[df['contact_id'].isin(ids_ignorar_contactos), 'id']

ids_sin_first_reply_created_at = df.loc[df['first_reply_created_at'].isna(), 'id']
ids_conversaciones_ignorar = pd.concat([ids_conversaciones_ignorar, ids_sin_first_reply_created_at]).unique()

cantidad_conversaciones_ignoradas_contactos = df['id'].isin(ids_conversaciones_ignorar).sum()

df = df[~df['id'].isin(ids_conversaciones_ignorar)]

#Serie con datos de registros ignorados por contactos
cantidad_conversaciones_festivos = df[df['holiday']]
#--

df = df[~df['holiday']]
cantidad_datos_filtrados = len(df)
df['weekday'] = df['created_at'].dt.weekday
promedios_24_h = (
    df.groupby([df['weekday'], df['created_at'].dt.to_period('D')]).size().groupby(level=0).mean().round(2)
)

# df_lunes = df[(df['created_at'].dt.weekday == 0)]
# promedio_lunes = df_lunes.groupby(df_lunes['created_at'].dt.to_period('D')).size().mean().round(2)

# df_martes = df[(df['created_at'].dt.weekday == 1)]
# promedio_martes = df_martes.groupby(df_martes['created_at'].dt.to_period('D')).size().mean().round(2)

# df_miercoles = df[(df['created_at'].dt.weekday == 2)]
# promedio_miercoles = df_miercoles.groupby(df_miercoles['created_at'].dt.to_period('D')).size().mean().round(2)

# df_jueves = df[(df['created_at'].dt.weekday == 3)]
# promedio_jueves = df_jueves.groupby(df_jueves['created_at'].dt.to_period('D')).size().mean().round(2)

# df_viernes = df[(df['created_at'].dt.weekday == 4)]
# promedio_viernes = df_viernes.groupby(df_viernes['created_at'].dt.to_period('D')).size().mean().round(2)

# df_sabado = df[(df['created_at'].dt.weekday == 5)]
# promedio_sabado = df_sabado.groupby(df_sabado['created_at'].dt.to_period('D')).size().mean().round(2)

# df_domingo = df[(df['created_at'].dt.weekday == 6)]
# promedio_domingo = df_domingo.groupby(df_domingo['created_at'].dt.to_period('D')).size().mean().round(2)


print(f"Cantidad datos antes de ignorar: {cantidad_datos_sin_filtrar}")
print(f"Cantidad conversaciones ignoradas por contactos y conversaciones sin tiempo de primera respuesta: {cantidad_conversaciones_ignoradas_contactos}")
print(f"Cantidad conversaciones ignoradas por festivos: {len(cantidad_conversaciones_festivos)}")

print(f"Cantidad datos despues de ignorar: {cantidad_datos_filtrados}\n")

print(f"Anio: {year_rp} - Mes: {month_rp}")
print(f"Promedios conversaciones del mes 24h: \n")
print(f"Lunes: {promedios_24_h[0]}")
print(f"Martes: {promedios_24_h[1]}")
print(f"Miercoles: {promedios_24_h[2]}")
print(f"Jueves: {promedios_24_h[3]}")
print(f"Viernes: {promedios_24_h[4]}")
print(f"Sabado: {promedios_24_h[5]}")
print(f"Domingo: {promedios_24_h[6]} \n")

print("Promedios hora laboral")

# agregas columna con weekday
df_habiles = df.copy()
df_habiles['weekday'] = df_habiles['created_at'].dt.weekday

df_habiles = df_habiles[
    ((df_habiles['weekday'] != 6) & (df_habiles['weekday'] != 5) & (df_habiles['created_at'].dt.hour >=12) & (df_habiles['created_at'].dt.hour <=22)) | (
        (df_habiles['weekday'] == 5) &
        (df_habiles['created_at'].dt.hour >= 13) &
        (df_habiles['created_at'].dt.hour <= 17)
    )
]

# agrupas por weekday y día
promedios = (
    df_habiles.groupby([df_habiles['weekday'], df_habiles['created_at'].dt.to_period('D')])
    .size()
    .groupby(level=0)  # promedio por weekday
    .mean()
    .round(2)
)

ids_conversaciones_validas = df['id'].unique()
promedios

Cantidad datos antes de ignorar: 1671
Cantidad conversaciones ignoradas por contactos y conversaciones sin tiempo de primera respuesta: 133
Cantidad conversaciones ignoradas por festivos: 15
Cantidad datos despues de ignorar: 1523

Anio: 2026 - Mes: 1
Promedios conversaciones del mes 24h:

Lunes: 145.5
Martes: 158.0
Miercoles: 138.0
Jueves: 120.0
Viernes: 101.33
Sabado: 25.0
Domingo: 7.0

Promedios hora laboral

weekday
0    142.00
1    152.00
2    132.00
3    114.00
4     98.67
5     20.67
dtype: float64

# Metrica  #2. Promedio de mensajes por hora

In [4]:

sentencia_messages = "SELECT * FROM messages WHERE created_at >= '2025-11-01'" 

df_all_messages = pd.read_sql(sentencia_messages, engine)

df_messages = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()
df_messages = df_messages.sort_values(['conversation_id', 'created_at'])

df_messages = df_messages[(df_messages['sender_type'].notna()) & (df_messages['sender_type'] != 'User')]

df_messages['weekday'] = df_messages['created_at'].dt.weekday

promedios_por_hora_24h = (df_messages.groupby([df_messages['weekday'], df_messages['created_at'].dt.to_period('h')]).size().groupby(level=0).mean().round(2))

print(f"Total mensajes de contactos en el mes: {len(df_messages)}\n")
print(f"Promedio mensajes de contactos en las 24h:")
print(f"Lunes: {promedios_por_hora_24h[0]}")
print(f"Martes: {promedios_por_hora_24h[1]}")
print(f"Miercoles: {promedios_por_hora_24h[2]}")
print(f"Jueves: {promedios_por_hora_24h[3]}")
print(f"Viernes: {promedios_por_hora_24h[4]}")
print(f"Sabado: {promedios_por_hora_24h[5]}")
print(f"Sabado: {promedios_por_hora_24h[6]} \n")


df_habiles_messag = df_messages[
    ((df_messages['weekday'] != 6) & (df_messages['weekday'] != 5) & (df_messages['created_at'].dt.hour >=12) & (df_messages['created_at'].dt.hour <=22)) | (
        (df_messages['weekday'] == 5) &
        (df_messages['created_at'].dt.hour >= 13) &
        (df_messages['created_at'].dt.hour <= 17)
    )
]
promedios_por_hora = (df_habiles_messag.groupby([df_habiles_messag['weekday'], df_habiles_messag['created_at'].dt.to_period('h')]).size().groupby(level=0).mean().round(2))
promedios_por_hora

print(f"Promedio mensajes de contactos en horario laboral:")
print(f"Lunes:{promedios_por_hora[0]}")
print(f"Martes: {promedios_por_hora[1]}")
print(f"Miercoles: {promedios_por_hora[2]}")
print(f"Jueves: {promedios_por_hora[3]}")
print(f"Viernes: {promedios_por_hora[4]}")
print(f"Sabado: {promedios_por_hora[5]}")

Total mensajes de contactos en el mes: 8907

Promedio mensajes de contactos en las 24h:
Lunes: 57.82
Martes: 57.17
Miercoles: 53.66
Jueves: 43.62
Viernes: 42.84
Sabado: 18.07
Sabado: 2.17

Promedio mensajes de contactos en horario laboral:
Lunes:79.55
Martes: 74.0
Miercoles: 76.18
Jueves: 66.05
Viernes: 56.27
Sabado: 32.64

## Hacer el promedio de primera respuesta solo de conversaciones que se crearon dentro del horario laboral

In [ ]:
# Promedio de primera respuesta de conversaciones que se iniciaron en cualquier hora y se calcula dependiendo de la la hora de la primera respuesta
# Por ejemplo: primer mensaje de usuario: miercoles 7pm; primera respuesta: 8:30am. Tiempo de primera respuesta = 90min


# Promedio de primera respuesta de conversaciones que se iniciaron solo en horario laboral, ignorando domingos, festivos y conversaciones que se crearon por fuera del horario laboral
# En este caso el ejemplo de arriba no aplica aqui porque la conversacion no se debe tomar en cuenta

# Metrica #3 Tiempo de Primera Respuesta

In [5]:
df_sin_inicio_plantilla = df[~df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False)].copy()

#6501, 6807
df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_localize('UTC')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_localize('UTC')

df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_convert('America/Bogota')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia = df_sin_inicio_plantilla['created_at'].dt.date == df_sin_inicio_plantilla['first_reply_created_at'].dt.date

def calcular_dia_distinto(row):
    inicio = row['created_at']
    primera_respuesta = row['first_reply_created_at']

    segundos = 0

    inicio_laboral_create_at = inicio.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    inicio_laboral_first_reply = primera_respuesta.replace(hour=7, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        inicio_laboral_create_at = inicio.replace(hour=8, minute=0, second=0, microsecond=0)
        fin_laboral_created_at = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
      
    if row['first_reply_created_at'].weekday() == 5:
        inicio_laboral_first_reply = primera_respuesta.replace(hour=8, minute=0, second=0, microsecond=0)

    if inicio >= inicio_laboral_create_at and inicio < fin_laboral_created_at and row['created_at'].weekday() != 6:
        segundos +=(fin_laboral_created_at-inicio).total_seconds()
    
    if primera_respuesta > inicio_laboral_first_reply:
        segundos +=(primera_respuesta - inicio_laboral_first_reply).total_seconds()
    
    return segundos

def calcular_mismo_dia(row):
    inicio = row['created_at']
    primera_respuesta = row['first_reply_created_at']

    segundos = 0

    fin_laboral = inicio.replace(hour=17, minute=0, second=0, microsecond=0)
    inicio_laboral = primera_respuesta.replace(hour=7, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        fin_laboral = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
        inicio_laboral = primera_respuesta.replace(hour=8, minute=0, second=0, microsecond=0)

    if inicio >= inicio_laboral and inicio < fin_laboral :
        segundos +=(primera_respuesta-inicio).total_seconds()
    
    if inicio < inicio_laboral and primera_respuesta <= fin_laboral:
        segundos +=(primera_respuesta-inicio_laboral).total_seconds()
    
    return max(segundos, 0)
    
    
df_sin_inicio_plantilla['tiempo_respuesta_segundos'] = np.where(
    mismo_dia,
    df_sin_inicio_plantilla.apply(calcular_mismo_dia, axis=1).round(2),
    df_sin_inicio_plantilla.apply(calcular_dia_distinto, axis=1).round(2)
)

df_sin_inicio_plantilla['tiempo_respuesta_minutos'] = (df_sin_inicio_plantilla['tiempo_respuesta_segundos'] / 60).round(2)
df_sin_inicio_plantilla['tiempo_respuesta_horas'] = (df_sin_inicio_plantilla['tiempo_respuesta_minutos'] / 60).round(2)

promedio_tiempo_respuesta_min = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].mean()
promedio_tiempo_respuesta_min


# print(df_sin_inicio_plantilla['tiempo_respuesta_minutos'].describe())
# v = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] ==  278.630000]
# v
# mitad = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] > 40]
# mitad.head(30)

print(df_sin_inicio_plantilla['tiempo_respuesta_minutos'].describe())
infiltrado = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] == 177.790000]
infiltrado

infiltrados = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] == 392.290000]
infiltrados

# count    1253.000000
# mean       45.813966
# std        41.296678
# min         0.100000
# 25%        14.650000
# 50%        33.440000
# 75%        67.100000
# max       278.630000

count    1253.000000
mean       45.813966
std        41.296678
min         0.100000
25%        14.650000
50%        33.440000
75%        67.100000
max       278.630000
Name: tiempo_respuesta_minutos, dtype: float64

Empty DataFrame
Columns: [id, account_id, inbox_id, status, assignee_id, created_at, updated_at, contact_id, display_id, contact_last_seen_at, agent_last_seen_at, additional_attributes, contact_inbox_id, uuid, identifier, last_activity_at, team_id, campaign_id, snoozed_until, custom_attributes, assignee_last_seen_at, first_reply_created_at, priority, sla_policy_id, waiting_since, cached_label_list, holiday, weekday, tiempo_respuesta_segundos, tiempo_respuesta_minutos, tiempo_respuesta_horas]
Index: []

[0 rows x 31 columns]

## Promedio primera respuesta conversaciones iniciadas con plantilla

In [7]:
# ids_caso_raro = [6175, 6877, 6214, 6057]
ids_conv_iniciadas_plantilla = df.loc[df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False),'id']

#ids_conv_iniciadas_plantilla = ids_conv_iniciadas_plantilla[~ids_conv_iniciadas_plantilla.isin(ids_caso_raro)]

df_messages_conv_ini_plantilla = df_all_messages[df_all_messages['conversation_id'].isin(ids_conv_iniciadas_plantilla)].copy()
df_messages_conv_ini_plantilla = df_messages_conv_ini_plantilla.sort_values(['conversation_id', 'created_at'])

primer_mensaje_contacto = df_messages_conv_ini_plantilla[(df_messages_conv_ini_plantilla['message_type'] == 0) & (~df_messages_conv_ini_plantilla['content'].isin(['system_resolved', 'system_timeout']))].groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'created_at_type_0'})

df_merge_tiempo_primer_mensaje_contacto = df_messages_conv_ini_plantilla.merge(primer_mensaje_contacto, on='conversation_id', how='inner')

df_mensajes_agente = df_merge_tiempo_primer_mensaje_contacto[
    (df_merge_tiempo_primer_mensaje_contacto['message_type'] == 1) &
    (df_merge_tiempo_primer_mensaje_contacto['private'] != True) &
    (df_merge_tiempo_primer_mensaje_contacto['created_at'] > df_merge_tiempo_primer_mensaje_contacto['created_at_type_0'])
]

df_primera_respuesta = (df_mensajes_agente.sort_values(['conversation_id', 'created_at']).groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'first_reply_created_at'}))

df_first_messages = primer_mensaje_contacto.merge(df_primera_respuesta,on='conversation_id',how='left')
df_first_messages = df_first_messages.rename(columns={'created_at_type_0': 'created_at'})

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_localize('UTC')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_localize('UTC')

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_convert('America/Bogota')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia_plantilla =  df_first_messages['created_at'].dt.date == df_first_messages['first_reply_created_at'].dt.date
df_first_messages['tiempo_respuesta_minutos'] = np.where(
    mismo_dia_plantilla,
    (df_first_messages.apply(calcular_mismo_dia, axis=1) / 60).round(2),
    (df_first_messages.apply(calcular_dia_distinto, axis=1) / 60).round(2)
)

promedio = df_first_messages['tiempo_respuesta_minutos'].mean() 
promedio

#v = df_first_messages[df_first_messages['tiempo_respuesta_minutos'] ==  197.010000]

total_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].sum()
cantidad_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].count()

total_inicio_plantilla
cantidad_inicio_plantilla

total_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].sum()
cantidad_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].count()

promedio_total = ((total_inicio_plantilla + total_sin_inicio_plantilla) / (cantidad_inicio_plantilla + cantidad_sin_inicio_plantilla)).round(2)
promedio_total




# df_first_messages

np.float64(44.13)

# Promedio primera respuesta conversaciones iniciadas solo en horario laboral

In [9]:
df_filtrado_sin_plantilla = df_sin_inicio_plantilla[
    (
        df_sin_inicio_plantilla['created_at'].dt.weekday.between(0, 4) &
        df_sin_inicio_plantilla['created_at'].dt.hour.between(7, 16)
    ) |
    (
        (df_sin_inicio_plantilla['created_at'].dt.weekday == 5) &
        df_sin_inicio_plantilla['created_at'].dt.hour.between(8, 11)
    )
]

total_minutos_df_filtrado_sin_pl = df_filtrado_sin_plantilla['tiempo_respuesta_minutos'].sum()
cantidad_df_filtrado_sin_pl = df_filtrado_sin_plantilla['tiempo_respuesta_minutos'].count()


promedio_laboral_sin_pl = df_filtrado_sin_plantilla['tiempo_respuesta_minutos'].mean()


df_filtrado_solo_pl = df_first_messages[
     (
        df_first_messages['created_at'].dt.weekday.between(0, 4) &
        df_first_messages['created_at'].dt.hour.between(7, 16)
    ) |
    (
        (df_first_messages['created_at'].dt.weekday == 5) &
        df_first_messages['created_at'].dt.hour.between(8, 11)
    )
]
total_minutos_df_solo_pl = df_filtrado_solo_pl['tiempo_respuesta_minutos'].sum()
cantidad_df_filtrado_solo_pl = df_filtrado_solo_pl['tiempo_respuesta_minutos'].count()


promedio_laboral = (total_minutos_df_filtrado_sin_pl + total_minutos_df_solo_pl) / (cantidad_df_filtrado_sin_pl+cantidad_df_filtrado_solo_pl)
promedio_laboral

np.float64(42.73432893716058)

# Metrica #4. Tiempo Promedio de Respuesta

Mediana del tiempo entre mensajes usuario → agente durante conversaciones activas.

In [10]:
sentencia_messages_contact_user = "SELECT * FROM messages WHERE created_at >= '2025-11-01'"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine)

df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])
df_messages_contact_user = df_messages_contact_user[df_messages_contact_user['conversation_id'].isin(ids_conversaciones_validas)]

df_messages_contact_user['next_message_type'] = df_messages_contact_user.groupby('conversation_id')['message_type'].shift(-1)
df_messages_contact_user['next_created_at'] = df_messages_contact_user.groupby('conversation_id')['created_at'].shift(-1)

respuestas = df_messages_contact_user[
    (df_messages_contact_user['message_type'] == 0) &
    (df_messages_contact_user['next_message_type'] == 1)
].copy()

mismo_dia_respuestas = respuestas['created_at'].dt.date == respuestas['next_created_at'].dt.date

def medir_dia_distinto(row):
    created_at = row['created_at']

    next_created_at = row['next_created_at']

    inicio_laboral_created_at = created_at.replace(hour=12, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = created_at.replace(hour=22, minute=0, second=0, microsecond=0)

    inicio_laboral_next = next_created_at.replace(hour=13, minute=0, second=0, microsecond=0)
    fin_laboral_next = next_created_at.replace(hour=17, minute=0, second=0, microsecond=0)
    if created_at.weekday() == 5:
        inicio_laboral_created_at = created_at.replace(hour=13, minute=0, second=0, microsecond=0)
        fin_laboral_created_at = created_at.replace(hour=17, minute=0, second=0, microsecond=0)

    if next_created_at.weekday() == 5:
        inicio_laboral_next = next_created_at.replace(hour=13, minute=0, second=0, microsecond=0)
        fin_laboral_next = next_created_at.replace(hour=17, minute=0, second=0, microsecond=0)

    segundos = 0
    if created_at >= inicio_laboral_created_at and created_at <= fin_laboral_created_at:
        segundos += (fin_laboral_created_at - created_at).total_seconds()
    
    if next_created_at >= inicio_laboral_next and next_created_at <= fin_laboral_next:
        segundos += (next_created_at - inicio_laboral_next).total_seconds()

    return max(segundos, 0)

def medir_mismo_dia(row):
    created_at = row['created_at']

    next_created_at = row['next_created_at']

    inicio_laboral_created_at = created_at.replace(hour=12, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = created_at.replace(hour=22, minute=0, second=0, microsecond=0)
    
    segundos = 0
    if created_at >= inicio_laboral_created_at and created_at <= fin_laboral_created_at:
        segundos += (next_created_at - created_at).total_seconds()
    else:
        segundos += (next_created_at - inicio_laboral_created_at).total_seconds()

    return max(segundos, 0)
respuestas['response_time_minutes'] = np.where(
    mismo_dia_respuestas,
    (respuestas.apply(medir_mismo_dia, axis=1) / 60).round(2),
    (respuestas.apply(medir_dia_distinto, axis=1) / 60).round(2)
)

# respuestas['response_time_minutes'] = ((respuestas['next_created_at'] - respuestas['created_at']).dt.total_seconds() / 60).round(2)

promedio_por_conversacion = (respuestas.groupby('conversation_id')['response_time_minutes'].mean()).round(2) 

promedio_por_conversacion


# respuestas

# infiltrado = respuestas[respuestas['conversation_id'] == 6143]
# v = respuestas['response_time_minutes'].describe()
# v
# infiltrado

conversation_id
5385    29.82
5386    46.50
5388     7.30
5389    20.13
5391    12.81
        ...
7035    31.07
7036     1.62
7037     0.34
7039     1.76
7041     1.96
Name: response_time_minutes, Length: 1426, dtype: float64

# Metrica #5. Conversión agendamiento (%)

In [11]:
df_iniciadas_agendamiento = df[
    df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

agendamiento_exitoso = df_iniciadas_agendamiento[df_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

iniciada_agendamiento = df_iniciadas_agendamiento[~df_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

porcentaje_agendamiento_exitoso = (len(agendamiento_exitoso) / len(df_iniciadas_agendamiento)) * 100
porcentaje_agendamiento_no_exitoso = (len(iniciada_agendamiento) / len(df_iniciadas_agendamiento)) * 100

df_no_iniciadas_agendamiento = df[
    ~df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

no_iniciadas_agendamiento_agendadas = df_no_iniciadas_agendamiento[df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso', na=False)]

no_iniciadas_agendamiento_no_agendadas = df_no_iniciadas_agendamiento[~df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso', na=False)]

len(no_iniciadas_agendamiento_no_agendadas)

porcentaje_no_iniciadas_agendamiento_agendadas = (len(no_iniciadas_agendamiento_agendadas) / len(df_no_iniciadas_agendamiento)) * 100
print(porcentaje_agendamiento_exitoso)
print(porcentaje_agendamiento_no_exitoso)

49.42084942084942
50.57915057915058

# Metrica #7. Índice de Eficiencia del Agente (AEI) [0–100]

In [ ]:
df = df.sort_values(['assignee_id'])
ids_contacts = df['contact_id'].unique()
df = df.sort_values(['contact_id'])
df.head()

# Metrica #9. Utilización de Capacidad (%)

In [ ]:
plantilla = [
    '¡Hola! 👋Bienvenido/a al canal exclusivo de asignación de citas de IMÁGENES DIAGNOSTICAS S.A.', 
    'Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda. ¿Podemos ayudarle en algo más?', 
    '¡Con gusto! Procederemos a cancelar su cita, por favor, envíanos los siguientes datos para gestionar mejor nuestra agenda y su solicitud.',
    'Recuerde que su lugar de atención es: Centro De Especialistas De Risaralda, Carrera 5 No 18-33,',
    'Para programar su cita, por favor indíquenos los siguientes datos:',
    'Lamentamos la demora en nuestra respuesta. Ayer enfrentamos una contingencia, pero ya estamos atendiendo su solicitud. ¡Gracias por su paciencia!',
    '¡Gracias por elegirnos! 💙 Esperamos poder atenderte nuevamente. Feliz día🌞 En caso de requerir algo adicional, escríbenos en cualquier momento. ¡Estamos para servirte! 😊',
    'Por la complejidad del procedimiento solicitado y su seguridad, requerimos que por favor, nos confirme los siguientes datos:', 
    '📌 Para la solicitud y agendamientos de citas a través del Hospital Universitario San Jorge',
    '📌 Para la solicitud y agendamientos de exámenes de Hemodinamia, agradecemos que por favor nos contacte a través del siguiente WhatsApp 3128345850.',
    'nuestros horarios de atención son de lunes a viernes de 7:00 a.m a 5:00 p.m sabados de 8:00 a.m a 12:00 pm domingos y festivos cerrado',
    'IMÁGENES DIAGNÓSTICAS S.A. 😊 agradece su comunicación y el interés en nuestros servicios.',
    '⌛ "Agradecemos su paciencia. Actualmente estamos recibiendo un volumen de usuarios mayor al habitual, por lo que estamos atendiendo los mensajes por orden de llegada.',
    'Nos permitimos informar que, para la solicitud y consulta de sus resultados',
    '¡Con gusto! Procederemos a reprogramar su cita, por favor, envíanos los siguientes datos para gestionar mejor nuestra agenda y su solicitud.'     
]



df_messages_agent = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()
df_messages_agent = df_messages_agent[
    ((df_messages_agent['created_at'].dt.weekday != 6) & (df_messages_agent['created_at'].dt.weekday != 5) & (df_messages_agent['created_at'].dt.hour >=12) & (df_messages_agent['created_at'].dt.hour <=22)) | (
        (df_messages_agent['created_at'].dt.weekday == 5) &
        (df_messages_agent['created_at'].dt.hour >= 13) &
        (df_messages_agent['created_at'].dt.hour <= 17)
    )
]

df_messages_agent = df_messages_agent[(df_messages_agent['sender_type'] == 'User') & (df_messages_agent['sender_id'] != 1)]

df_messages_agent = df_messages_agent.sort_values(['conversation_id', 'created_at'])
#tiempo estandar de escritura de un mensaje 40 PPM (palabras por minuto)
ppm = 40

df_messages_agent['cantidad_palabras'] = df_messages_agent['content'].fillna("").str.split().str.len()
df_messages_agent['tiempo_segundos_mensaje'] = (df_messages_agent['cantidad_palabras'] / ppm) * 60 

df_messages_agent['created_at'] = pd.to_datetime(df_messages_agent['created_at'])


df_messages_agent['content'] = df_messages_agent['content'].astype(str)

plantillas_escaped = [re.escape(p) for p in plantilla] 

patron = "|".join(plantillas_escaped)
df_messages_agent = df_messages_agent[~df_messages_agent['content'].str.contains(patron, na=False)]

cantidad_segundos_diarios = (
    df_messages_agent
    .groupby([
        df_messages_agent['created_at'].dt.to_period('D'), 
        'sender_id'
    ])['tiempo_segundos_mensaje'].sum()
)


cantidad_segundos_diarios.head(50)
# 2026-01-02  6.0           9409.5
#             10.0          6406.5
#             12.0          1542.0
# 2026-01-03  10.0          3936.0
#             12.0          1036.5
# 2026-01-05  6.0          15273.0
#             10.0         13510.5
#             11.0            13.5
#             12.0          2620.5
# 2026-01-06  6.0           8989.5
#             10.0         11572.5
#             11.0             9.0
#             12.0          4155.0
# 2026-01-07  6.0          22065.0

created_at  sender_id
2026-01-02  6.0          2922.0
            10.0         2377.5
            12.0         1218.0
2026-01-03  10.0         1881.0
            12.0          450.0
2026-01-05  6.0          4062.0
            10.0         4383.0
            11.0           13.5
            12.0         1906.5
2026-01-06  6.0          2332.5
            10.0         3913.5
            11.0            9.0
            12.0         2629.5
2026-01-07  6.0          6297.0
            9.0            24.0
            10.0         3904.5
            11.0           60.0
            12.0         2758.5
2026-01-08  6.0          4360.5
            10.0         3292.5
            12.0         3006.0
2026-01-09  6.0          3429.0
            10.0         3642.0
            12.0         1828.5
2026-01-10  6.0          2463.0
2026-01-13  6.0          4845.0
            10.0         4176.0
            12.0         2005.5
2026-01-14  6.0          4596.0
            10.0         3589.5
            12.0         2382.0
2026-01-15  6.0          4938.0
            10.0         3706.5
            12.0         2863.5
2026-01-16  6.0          3546.0
            10.0         3486.0
            12.0         2085.0
2026-01-17  10.0         1320.0
            12.0         1243.5
2026-01-19  6.0          2686.5
            10.0         1951.5
            12.0         1977.0
            13.0         3814.5
            15.0          661.5
Name: tiempo_segundos_mensaje, dtype: float64

In [295]:
df_sin_pl.head(40)

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,...,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment,cantidad_palabras,tiempo_segundos_mensaje
80681,91784,"*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 505.200*\r\n\r\nPara continuar, solo necesito la orden médica si la tiene.\r\n\r\n*¿Agendamos la cita?*",1,1,5385,1,2026-01-02 12:23:01.895567,2026-01-02 12:23:01.895567,False,0,...,0,None,User,10.0,None,{},"*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 505.200*\r\n\r\nPara continuar, solo necesito la orden médica si la tiene.\r\n\r\n*¿Agendamos la cita?*",{},23,34.5
87292,92187,La disponibilidad para la tomografía se puede realizar de un día para otro.,1,1,5385,1,2026-01-02 14:09:24.308731,2026-01-02 14:09:24.308731,False,0,...,0,None,User,10.0,None,{},La disponibilidad para la tomografía se puede realizar de un día para otro.,{},13,19.5
87647,92415,*¿Agendamos la cita?*,1,1,5385,1,2026-01-02 15:22:32.657356,2026-01-02 15:22:32.657356,False,0,...,0,None,User,12.0,None,{},*¿Agendamos la cita?*,{},3,4.5
87934,92545,quedamos atentos,1,1,5385,1,2026-01-02 16:14:41.865329,2026-01-02 16:14:41.865329,False,0,...,0,None,User,6.0,None,{},quedamos atentos,{},2,3.0
89668,93506,"Hola buenos días, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",1,1,5385,1,2026-01-03 14:19:50.194918,2026-01-03 14:19:50.194918,False,0,...,0,None,User,12.0,None,{},"Hola buenos días, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",{},21,31.5
86674,91799,Debe enviar por favor resultado de creatinina (no mayor a 30 dias),1,1,5386,1,2026-01-02 12:24:09.647656,2026-01-02 12:24:09.647656,False,0,...,0,None,User,10.0,None,{},Debe enviar por favor resultado de creatinina (no mayor a 30 dias),{},12,18.0
88048,92603,"quedamos atentos a los datos, encuesta y resultado de la creatinina vigente, que no sea mayor a 30 días solicitados previamente para la asignación de la cita",1,1,5386,1,2026-01-02 16:39:53.842862,2026-01-02 16:39:53.842862,False,0,...,0,None,User,6.0,None,{},"quedamos atentos a los datos, encuesta y resultado de la creatinina vigente, que no sea mayor a 30 días solicitados previamente para la asignación de la cita",{},27,40.5
88108,92629,"Lamentablemente, no podemos programar la cita sin el resultado de la creatinina. Por favor, cuando lo tengas, comunícate por este mismo medio. Estaremos pendientes.",1,1,5386,1,2026-01-02 16:50:55.951631,2026-01-02 16:50:55.951631,False,0,...,0,None,User,10.0,None,{},"Lamentablemente, no podemos programar la cita sin el resultado de la creatinina. Por favor, cuando lo tengas, comunícate por este mismo medio. Estaremos pendientes.",{},24,36.0
88053,92636,"Claro que si, se toman agendamientos hasta las 12 del medio dia.",1,1,5386,1,2026-01-02 16:52:00.819017,2026-01-02 16:52:00.819017,False,0,...,0,None,User,10.0,None,{},"Claro que si, se toman agendamientos hasta las 12 del medio dia.",{},12,18.0
89610,93502,"Hola buenos días, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",1,1,5386,1,2026-01-03 14:19:20.588979,2026-01-03 14:19:20.588979,False,0,...,0,None,User,12.0,None,{},"Hola buenos días, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",{},21,31.5
90076,93778,"Lamentamos informarle que no podemos proceder con la asignación sin el resultado, ya que es esencial para el aval médico y para asignar la cita. Cuando lo tenga, por favor contáctenos para continuar con el proceso. Estaremos muy pendientes.",1,1,5386,1,2026-01-03 16:49:47.853832,2026-01-03 16:49:47.853832,False,0,...,0,None,User,12.0,None,{},"Lamentamos informarle que no podemos proceder con la asignación sin el resultado, ya que es esencial para el aval médico y para asignar la cita. Cuando lo tenga, por favor contáctenos para continuar con el proceso. Estaremos muy pendientes.",{},39,58.5
90266,93925,se envia plantilla,1,1,5386,1,2026-01-05 12:10:08.521826,2026-01-05 12:10:08.521826,True,0,...,0,None,User,6.0,None,{},se envia plantilla,{},3,4.5
86250,91819,Indícanos cómo podemos ayudarte y te responderemos lo antes posible.,1,1,5388,1,2026-01-02 12:26:41.689501,2026-01-02 12:26:41.689501,False,0,...,0,None,User,10.0,None,{},Indícanos cómo podemos ayudarte y te responderemos lo antes posible.,{},10,15.0
84420,91884,numero de documento por favor,1,1,5388,1,2026-01-02 12:39:56.518663,2026-01-02 12:39:56.518663,False,0,...,0,None,User,6.0,None,{},numero de documento por favor,{},5,7.5
86870,91913,"No se preocupe esta bien agendada, el código interno lo nombra de esa manera.",1,1,5388,1,2026-01-02 12:42:56.050390,2026-01-02 12:42:56.050390,False,0,...,0,None,User,10.0,None,{},"No se preocupe esta bien agendada, el código interno lo nombra de esa manera.",{},14,21.0
77912,91824,"*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 277.900*\r\n\r\nPara continuar, solo necesito la orden médica si la tiene.\r\n\r\n*¿Agendamos la cita?*",1,1,5389,1,2026-01-02 12:30:43.803104,2026-01-02 12:30:43.803104,False,0,...,0,None,User,10.0,None,{},"*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 277.900*\r\n\r\nPara continuar, solo necesito la orden médica si la tiene.\r\n\r\n*¿Agendamos la cita?*",{},23,34.5
87151,92047,None,1,1,5389,1,2026-01-02 13:29:54.399581,2026-01-02 13:30:35.234554,False,0,...,0,None,User,10.0,None,{},None,{},0,0.0
87128,92050,"Recomendaciones: presentarse 15 minutos antes, con orden médica.",1,1,5389,1,2026-01-02 13:30:28.332806,2026-01-02 13:30:28.332806,False,0,...,0,None,User,10.0,None,{},"Recomendaciones: presentarse 15 minutos antes, con orden médica.",{},8,12.0
87130,92053,"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",1,1,5389,1,2026-01-02 13:30:40.249412,2026-01-02 13:30:40.249412,False,0,...,0,None,User,10.0,None,{},"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",{},24,36.0
87195,92087,"Gracias por la información. Por favor, permítame unos minutos mientras procesamos sus datos para continuar con su solicitud.",1,1,5391,1,2026-01-02 13:38:22.784732,2026-01-02 13:38:22.784732,False,0,...,0,None,User,6.0,None,{},"Gracias por la información. Por favor, permítame unos minutos mientras procesamos sus datos para continuar con su solicitud.",{},18,27.0
87316,92161,None,1,1,5391,1,2026-01-02 13:59:48.264517,2026-01-02 14:00:27.627371,False,0,...,0,None,User,10.0,None,{},None,{},0,0.0
87288,92162,"RECOMENDACIONES: TENER VEJIGA LLENA ( 1 HORAS ANTES TOMAR ABUNDANTE AGUA), PRESENTARSE 15 MINUTOS ANTES, CON ORDEN MÉDICA.",1,1,5391,1,2026-01-02 14:00:26.469490,2026-01-02 14:00:26.469490,False,0,...,0,None,User,10.0,None,{},"RECOMENDACIONES: TENER VEJIGA LLENA ( 1 HORAS ANTES TOMAR ABUNDANTE AGUA), PRESENTARSE 15 MINUTOS ANTES, CON ORDEN MÉDICA.",{},18,27.0
87318,92164,"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",1,1,5391,1,2026-01-02 14:00:40.310439,2026-01-02 14:00:40.310439,False,0,...,0,None,User,10.0,None,{},"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",{},24,36.0
87236,92112,TARIFA BONO,1,1,5392,1,2026-01-02 13:44:16.721434,2026-01-02 13:44:16.721434,True,0,...,0,None,User,6.0,None,{},TARIFA BONO,{},2,3.0
87354,92185,"Gracias por la información. Por favor, permítame unos minutos mientras procesamos sus datos para continuar con su solicitud.",1,1,5392,1,2026-01-02 14:07:55.903384,2026-01-02 14:07:55.903384,False,0,...,0,None,User,10.0,None,{},"Gracias por la información. Por favor, permítame unos minutos mientras procesamos sus datos para continuar con su solicitud.",{},18,27.0
87585,92346,"Recomendaciones: presentarse 15 minutos antes, con orden médica //TENER VEJIGA LLENA 1 HORA ANTES TOMAR ABUNDANTE AGUA.",1,1,5392,1,2026-01-02 15:09:18.584450,2026-01-02 15:09:18.584450,False,0,...,0,None,User,10.0,None,{},"Recomendaciones: presentarse 15 minutos antes, con orden médica //TENER VEJIGA LLENA 1 HORA ANTES TOMAR ABUNDANTE AGUA.",{},17,25.5
87587,92349,"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",1,1,5392,1,2026-01-02 15:09:32.065548,2026-01-02 15:09:32.065548,False,0,...,0,None,User,10.0,None,{},"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",{},24,36.0
87875,92475,None,1,1,5392,1,2026-01-02 15:38:42.890119,2026-01-02 15:38:46.303020,False,0,...,0,None,User,10.0,None,{},None,{},0,0.0
87679,92499,"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",1,1,5392,1,2026-01-02 15:52:55.933753,2026-01-02 15:52:55.933753,False,0,...,0,None,User,10.0,None,{},"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",{},24,36.0
87771,92445,"*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 525.000 simple y $ 825.000 contrastada .*\r\n\r\nPara continuar, solo necesito la orden médica si la tiene.\r\n\r\n*¿Agendamos la cita?*",1,1,5393,1,2026-01-02 15:30:34.150600,2026-01-02 15:30:34.150600,False,0,...,0,None,User,6.0,None,{},"*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 525.000 simple y $ 825.000 contrastada .*\r\n\r\nPara continuar, solo necesito la orden médica si la tiene.\r\n\r\n*¿Agendamos la cita?*",{},29,43.5
88540,92950,"Hola buenas tardes, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",1,1,5393,1,2026-01-02 19:12:47.386121,2026-01-02 19:12:47.386121,False,0,...,0,None,User,12.0,None,{},"Hola buenas tardes, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",{},21,31.5
77919,91856,estamos atentos a los datos solicitados para programar su cita,1,1,5394,1,2026-01-02 12:37:06.553405,2026-01-02 12:37:06.553405,False,0,...,0,None,User,6.0,None,{},estamos atentos a los datos solicitados para programar su cita,{},10,15.0
86883,91980,"Gracias por la información. Por favor, permítame unos minutos mientras procesamos sus datos para continuar con su solicitud.",1,1,5394,1,2026-01-02 13:06:44.902270,2026-01-02 13:06:44.902270,False,0,...,0,None,User,10.0,None,{},"Gracias por la información. Por favor, permítame unos minutos mientras procesamos sus datos para continuar con su solicitud.",{},18,27.0
87118,92009,None,1,1,5394,1,2026-01-02 13:15:10.187750,2026-01-02 13:15:15.220979,False,0,...,0,None,User,10.0,None,{},None,{},0,0.0
87120,92013,"Recomendaciones: Llegar 15 minutos antes, con orden médica,resultado de creatinina, en ayuno y acompañante.",1,1,5394,1,2026-01-02 13:16:28.018194,2026-01-02 13:16:28.018194,False,0,...,0,None,User,10.0,None,{},"Recomendaciones: Llegar 15 minutos antes, con orden médica,resultado de creatinina, en ayuno y acompañante.",{},14,21.0
87137,92015,"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",1,1,5394,1,2026-01-02 13:16:58.674037,2026-01-02 13:16:58.674037,False,0,...,0,None,User,10.0,None,{},"Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda.\r\n\r\n¿Podemos ayudarle en algo más?",{},24,36.0
86253,91839,que doppler le menciono el médico?,1,1,5398,1,2026-01-02 12:32:32.066804,2026-01-02 12:32:32.066804,False,0,...,0,None,User,10.0,None,{},que doppler le menciono el médico?,{},6,9.0
76728,91843,"Permitame un momento por favor, estoy revisando si la realizamos.",1,1,5398,1,2026-01-02 12:35:04.847947,2026-01-02 12:35:04.847947,False,0,...,0,None,User,10.0,None,{},"Permitame un momento por favor, estoy revisando si la realizamos.",{},10,15.0
80682,91874,*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 224.400*\r\n\r\n*¿Agendamos la cita?*,1,1,5398,1,2026-01-02 12:39:29.944786,2026-01-02 12:39:29.944786,False,0,...,0,None,User,10.0,None,{},*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 224.400*\r\n\r\n*¿Agendamos la cita?*,{},13,19.5
86947,91922,La citas con el Dr Victor estan apartir del 20 de enero.,1,1,5398,1,2026-01-02 12:44:26.175695,2026-01-02 12:44:26.175695,False,0,...,0,None,User,10.0,None,{},La citas con el Dr Victor estan apartir del 20 de enero.,{},12,18.0

In [293]:
df_messages_agent.head(20)

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,...,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment,cantidad_palabras,tiempo_segundos_mensaje
85156,91783,¡Hola! 👋Bienvenido/a al canal exclusivo de asignación de citas de IMÁGENES DIAGNOSTICAS S.A. 😊 Soy Viviana Ocampo y estaré encantada de ayudarte.,1,1,5385,1,2026-01-02 12:22:49.418219,2026-01-02 12:22:49.418219,False,0,...,0,None,User,10.0,None,{},¡Hola! 👋Bienvenido/a al canal exclusivo de asignación de citas de IMÁGENES DIAGNOSTICAS S.A. 😊 Soy Viviana Ocampo y estaré encantada de ayudarte.,{},22,33.0
80681,91784,"*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 505.200*\r\n\r\nPara continuar, solo necesito la orden médica si la tiene.\r\n\r\n*¿Agendamos la cita?*",1,1,5385,1,2026-01-02 12:23:01.895567,2026-01-02 12:23:01.895567,False,0,...,0,None,User,10.0,None,{},"*¡Con gusto!*\r\n\r\nEl examen tiene un valor de *$ 505.200*\r\n\r\nPara continuar, solo necesito la orden médica si la tiene.\r\n\r\n*¿Agendamos la cita?*",{},23,34.5
87292,92187,La disponibilidad para la tomografía se puede realizar de un día para otro.,1,1,5385,1,2026-01-02 14:09:24.308731,2026-01-02 14:09:24.308731,False,0,...,0,None,User,10.0,None,{},La disponibilidad para la tomografía se puede realizar de un día para otro.,{},13,19.5
87647,92415,*¿Agendamos la cita?*,1,1,5385,1,2026-01-02 15:22:32.657356,2026-01-02 15:22:32.657356,False,0,...,0,None,User,12.0,None,{},*¿Agendamos la cita?*,{},3,4.5
87934,92545,quedamos atentos,1,1,5385,1,2026-01-02 16:14:41.865329,2026-01-02 16:14:41.865329,False,0,...,0,None,User,6.0,None,{},quedamos atentos,{},2,3.0
89668,93506,"Hola buenos días, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",1,1,5385,1,2026-01-03 14:19:50.194918,2026-01-03 14:19:50.194918,False,0,...,0,None,User,12.0,None,{},"Hola buenos días, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",{},21,31.5
86431,91785,¡Hola! 👋Bienvenido/a al canal exclusivo de asignación de citas de IMÁGENES DIAGNOSTICAS S.A. 😊 Soy Viviana Ocampo y estaré encantada de ayudarte.,1,1,5386,1,2026-01-02 12:23:20.736038,2026-01-02 12:23:20.736038,False,0,...,0,None,User,10.0,None,{},¡Hola! 👋Bienvenido/a al canal exclusivo de asignación de citas de IMÁGENES DIAGNOSTICAS S.A. 😊 Soy Viviana Ocampo y estaré encantada de ayudarte.,{},22,33.0
85881,91786,"Para programar su cita, por favor indíquenos los siguientes datos:\r\n\r\n📛 Nombres y apellidos \r\n\r\n🆔 Tipo y Número de documento (sin puntos ni comas ni espacios) \r\n\r\n🎂 Fecha de nacimiento \r\n\r\n🏡 Dirección \r\n\r\n📞 Dos números telefónicos \r\n\r\n📧 Correo electrónico \r\n\r\n🏥 EPS a la que perteneces 🏛️ Entidad por la que realizas el procedimiento por favor, nos envía una foto de la orden médica y/o autorización (SI APLICA) para verificar y brindarte toda la información necesaria para la programación y realización del examen solicitado.",1,1,5386,1,2026-01-02 12:23:32.412691,2026-01-02 12:23:32.412691,False,0,...,0,None,User,10.0,None,{},"Para programar su cita, por favor indíquenos los siguientes datos:\r\n\r\n📛 Nombres y apellidos \r\n\r\n🆔 Tipo y Número de documento (sin puntos ni comas ni espacios) \r\n\r\n🎂 Fecha de nacimiento \r\n\r\n🏡 Dirección \r\n\r\n📞 Dos números telefónicos \r\n\r\n📧 Correo electrónico \r\n\r\n🏥 EPS a la que perteneces 🏛️ Entidad por la que realizas el procedimiento por favor, nos envía una foto de la orden médica y/o autorización (SI APLICA) para verificar y brindarte toda la información necesaria para la programación y realización del examen solicitado.",{},83,124.5
86674,91799,Debe enviar por favor resultado de creatinina (no mayor a 30 dias),1,1,5386,1,2026-01-02 12:24:09.647656,2026-01-02 12:24:09.647656,False,0,...,0,None,User,10.0,None,{},Debe enviar por favor resultado de creatinina (no mayor a 30 dias),{},12,18.0
86739,91800,"Por la complejidad del procedimiento solicitado y su seguridad, requerimos que por favor, nos confirme los siguientes datos: \r\n \r\n🦾 Posee algún elemento metálico en el cuerpo (tornillos, platinas, tatuajes recientes, ortodoncia, prótesis u otros) \r\n❤️‍🩹marcapasos y/o implantes de oídos \r\n🚪 Sufre de claustrofobia \r\n⚖️ ¿Cuál es su peso actual? \r\n💊 Presenta alguna alergia a medicamentos, alimentos u otros. \r\n❤️ ¿Sufre de hipertensión o diabetes?",1,1,5386,1,2026-01-02 12:24:16.350320,2026-01-02 12:24:16.350320,False,0,...,0,None,User,10.0,None,{},"Por la complejidad del procedimiento solicitado y su seguridad, requerimos que por favor, nos confirme los siguientes datos: \r\n \r\n🦾 Posee algún elemento metálico en el cuerpo (tornillos, platinas, tatuajes recientes, ortodoncia, prótesis u otros) \r\n❤️‍🩹marcapasos y/o implantes de oídos \r\n🚪 Sufre de claustrofobia \r\n⚖️ ¿Cuál es su peso actual? \r\n💊 Presenta alguna alergia a medicamentos, alimentos u otros. \r\n❤️ ¿Sufre de hipertensión o diabetes?",{},64,96.0
88048,92603,"quedamos atentos a los datos, encuesta y resultado de la creatinina vigente, que no sea mayor a 30 días solicitados previamente para la asignación de la cita",1,1,5386,1,2026-01-02 16:39:53.842862,2026-01-02 16:39:53.842862,False,0,...,0,None,User,6.0,None,{},"quedamos atentos a los datos, encuesta y resultado de la creatinina vigente, que no sea mayor a 30 días solicitados previamente para la asignación de la cita",{},27,40.5
88108,92629,"Lamentablemente, no podemos programar la cita sin el resultado de la creatinina. Por favor, cuando lo tengas, comunícate por este mismo medio. Estaremos pendientes.",1,1,5386,1,2026-01-02 16:50:55.951631,2026-01-02 16:50:55.951631,False,0,...,0,None,User,10.0,None,{},"Lamentablemente, no podemos programar la cita sin el resultado de la creatinina. Por favor, cuando lo tengas, comunícate por este mismo medio. Estaremos pendientes.",{},24,36.0
88053,92636,"Claro que si, se toman agendamientos hasta las 12 del medio dia.",1,1,5386,1,2026-01-02 16:52:00.819017,2026-01-02 16:52:00.819017,False,0,...,0,None,User,10.0,None,{},"Claro que si, se toman agendamientos hasta las 12 del medio dia.",{},12,18.0
89610,93502,"Hola buenos días, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",1,1,5386,1,2026-01-03 14:19:20.588979,2026-01-03 14:19:20.588979,False,0,...,0,None,User,12.0,None,{},"Hola buenos días, esto es un recordatorio de que tiene una conversación abierta con Imágenes Diagnósticas, desea continuar con esta conversación?",{},21,31.5
90076,93778,"Lamentamos informarle que no podemos proceder con la asignación sin el resultado, ya que es esencial para el aval médico y para asignar la cita. Cuando lo tenga, por favor contáctenos para continuar con el proceso. Estaremos muy pendientes.",1,1,5386,1,2026-01-03 16:49:47.853832,2026-01-03 16:49:47.853832,False,0,...,0,None,User,12.0,None,{},"Lamentamos informarle que no podemos proceder con la asignación sin el resultado, ya que es esencial para el aval médico y para asignar la cita. Cuando lo tenga, por favor contáctenos para continuar con el proceso. Estaremos muy pendientes.",{},39,58.5
90266,93925,se envia plantilla,1,1,5386,1,2026-01-05 12:10:08.521826,2026-01-05 12:10:08.521826,True,0,...,0,None,User,6.0,None,{},se envia plantilla,{},3,4.5
86250,91819,Indícanos cómo podemos ayudarte y te responderemos lo antes posible.,1,1,5388,1,2026-01-02 12:26:41.689501,2026-01-02 12:26:41.689501,False,0,...,0,None,User,10.0,None,{},Indícanos cómo podemos ayudarte y te responderemos lo antes posible.,{},10,15.0
84420,91884,numero de documento por favor,1,1,5388,1,2026-01-02 12:39:56.518663,2026-01-02 12:39:56.518663,False,0,...,0,None,User,6.0,None,{},numero de documento por favor,{},5,7.5
86870,91913,"No se preocupe esta bien agendada, el código interno lo nombra de esa manera.",1,1,5388,1,2026-01-02 12:42:56.050390,2026-01-02 12:42:56.050390,False,0,...,0,None,User,10.0,None,{},"No se preocupe esta bien agendada, el código interno lo nombra de esa manera.",{},14,21.0
86949,91924,"¡Gracias por elegirnos! 💙 Esperamos poder atenderte nuevamente. Feliz día🌞 En caso de requerir algo adicional, escríbenos en cualquier momento. ¡Estamos para servirte! 😊",1,1,5388,1,2026-01-02 12:45:05.622848,2026-01-02 12:45:05.622848,False,0,...,0,None,User,10.0,None,{},"¡Gracias por elegirnos! 💙 Esperamos poder atenderte nuevamente. Feliz día🌞 En caso de requerir algo adicional, escríbenos en cualquier momento. ¡Estamos para servirte! 😊",{},24,36.0

### Celula consultar datos

In [ ]:
ids_caso_raro = [6175, 6877, 6214, 6057]
sentencia_messages_contact_user = "SELECT * FROM messages WHERE id = 1038"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine) 

df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_localize('UTC')
df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_convert('America/Bogota')

df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])

df_messages_contact_user.head(90)

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,source_id,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment
0,1038,"📌 Para la solicitud y agendamientos de citas a través del Hospital Universitario San Jorge, agradecemos que por favor nos contacte a través del siguiente WhatsApp 3155311608 y/o al teléfono al 606 3320000.",1,1,122,1,2025-06-24 16:12:25.896861-05:00,2025-06-24 21:12:25.896861,False,0,None,0,None,None,None,None,{},"📌 Para la solicitud y agendamientos de citas a través del Hospital Universitario San Jorge, agradecemos que por favor nos contacte a través del siguiente WhatsApp 3155311608 y/o al teléfono al 606 3320000.",{}